# LAB-EXERCISE-7

#### Create two 3×3 matrices using the random function in Numpy and perform the following operations.
- Product (prod)
- Multiplication (multiply)
- Dot Product (dot)

In [11]:
import numpy as np

# CREATING MARTIX 3 X 3 
__martix_1__ = np.random.randint(30, size=(3,3))
__martix_2__ = np.random.randint(30, size=(3, 3))

# PERFORMING THE SPECIFIED OPERATIONS 
product_result = np.prod([__martix_1__,__martix_2__], axis=0)  
multiply_result = np.multiply(__martix_1__, __martix_2__)  
dot_product_result = np.dot(__martix_1__, __martix_2__) 

print("MATRIX-1:")
print(__martix_1__)
print("\nMATRIX-2:")
print(__martix_2__)

print("\nPRODUCT OF MATRIX 1:")
print(product_result)

print("\nMULTIPLICATION :")
print(multiply_result)

print("\nDOT PRODUCT :")
print(dot_product_result)


MATRIX-1:
[[ 1 27  8]
 [ 7 13  4]
 [11 16 10]]

MATRIX-2:
[[ 5 22 23]
 [ 7 19  8]
 [ 7  2 24]]

PRODUCT OF MATRIX 1:
[[  5 594 184]
 [ 49 247  32]
 [ 77  32 240]]

MULTIPLICATION :
[[  5 594 184]
 [ 49 247  32]
 [ 77  32 240]]

DOT PRODUCT :
[[250 551 431]
 [154 409 361]
 [237 566 621]]


#### Perform the following set operations using the Numpy functions.
- Union
- Intersection
- Set difference
- XOR

In [3]:
import numpy as np

# Create two NumPy arrays as sets
set1 = np.array([1, 2, 3, 4, 5])
set2 = np.array([3, 4, 5, 6, 7])

# Union
union_result = np.union1d(set1, set2)

# Intersection
intersection_result = np.intersect1d(set1, set2)

# Set difference (set1 - set2)
set_difference_result = np.setdiff1d(set1, set2)

# XOR 
xor_result = np.setxor1d(set1, set2)

print("SET-1 :", set1)
print("SET-2 :", set2)

print("\nUNION :", union_result)
print("INTERSECTION :", intersection_result)
print("SET DIFFERECE (SET-1 - SET-2):", set_difference_result)
print("XOR :", xor_result)


SET-1 : [1 2 3 4 5]
SET-2 : [3 4 5 6 7]

UNION : [1 2 3 4 5 6 7]
INTERSECTION : [3 4 5]
SET DIFFERECE (SET-1 - SET-2): [1 2]
XOR : [1 2 6 7]


#### Create a 1D array using Random function and perform the following operations.
- Cumulative sum
- Cumulative Product
- Discrete difference (with n=3)
- Find the unique elements from the array

In [12]:
import numpy as np

# Create a random 1D array with 10 elements
random_array = np.random.randint(50, size=(5))

# Cumulative sum
cumulative_sum = np.cumsum(random_array)

# Cumulative product
cumulative_product = np.cumprod(random_array)

# Discrete difference with n=3
discrete_difference = np.diff(random_array, n=3)

# Find unique elements
unique_elements = np.unique(random_array)

print("RANDOM ARRAY :")
print(random_array)

print("\nCUMMULITIVE SUM :")
print(cumulative_sum)

print("\nCUMMILITIVE PRODUCT :")
print(cumulative_product)

print("\nDISCREATE DIFFERENCE:")
print(discrete_difference)

print("\nUNIQUE ELEMENTS :")
print(unique_elements)


RANDOM ARRAY :
[22 40 23 16 26]

CUMMULITIVE SUM :
[ 22  62  85 101 127]

CUMMILITIVE PRODUCT :
[     22     880   20240  323840 8419840]

DISCREATE DIFFEREnCE:
[45  7]

UNIQUE ELEMENTS :
[16 22 23 26 40]


#### Create two 1D array and perform the Addition using zip(), add() and user defined function (frompyfunc()) 

In [17]:
x = [12, 24, 30, 41]
y = [49, 53, 62, 77]
z = []

for i, j in zip(x, y):
  z.append(i + j)
print("ZIPPED ARRAY OF X AND Y :   ",z)

x = [91, 42, 33, 54]
y = [50, 62, 71 ,88]
res = np.add(x, y)
print("ADDITION OF TWO ARRAYS ARE : ",res)


def myadd(x, y):
  return x+y

myadd = np.frompyfunc(myadd, 2, 1)

print("USER DEFINIED FUNCTIONS  ",myadd([1, 2, 3, 4], [5, 6, 7, 8]))


ZIPPED ARRAY OF X AND Y :    [61, 77, 92, 118]
ADDITION OF TWO ARRAYS ARE :  [141 104 104 142]
USER DEFINIED FUNCTIONS   [6 8 10 12]


#### Find the LCM (Least Common Multiple) and GCD (Greatest Common Divisor) of an array of elements using reduce().


In [15]:
import numpy as np
from functools import reduce

# Define a function to calculate the GCD of two numbers
def gcd(x, y):
    while y != 0:
        x, y = y, x % y
    return x

# Define a function to calculate the LCM of two numbers
def lcm(x, y):
    return x * y // gcd(x, y)

# Define an array of elements
arr = np.array([12, 18, 24, 36])

# Calculate the GCD of the array elements using reduce
gcd_result = reduce(gcd, arr)

# Calculate the LCM of the array elements using reduce
lcm_result = reduce(lcm, arr)

# Print the results
print(f"GCD OF THE ARRAY ELEMENT : {gcd_result}")
print(f"LCM OF THE ARRAY ELEMENT : {lcm_result}")



GCD OF THE ARRAY ELEMENT : 6
LCM OF THE ARRAY ELEMENT : 72
